services:
  dashboard:
    image: aloussase69/hestia:latest
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8080:${PORT:-8080}"
    environment:
      HESTIA_POSTGRES_URL: jdbc:postgresql://db:5432/postgres?user=postgres&password=postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: "postgres:17"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
      POSTGRES_DB: "${DB_NAME:-postgres}"
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
